name: webstore-build

on:
  workflow_dispatch:

jobs:
  build:
    name: 'Build and publish our app'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the app
        run: dotnet build --configuration Release

    


