name: webstore-build

on:
  workflow_dispatch:

jobs:
  build:
    name: 'Build and publish our app'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with: dotnet-version: '8.0.x' # Replace with your actual .NET version

      #- name: Restore dependencies
        #run: dotnet restore

      #- name: Build the app
        #run: dotnet build --configuration Release

    


